// src/components/AbaCards.tsx
const cards = [
    {
        bgColor: "bg-[var(--blue)]",
        title: "1. Desenvolvimento de habilidades sociais e de comunicacao",
        description:
            "A ABA ajuda a ensinar formas eficazes de se comunicar, seja por meio da fala, gestos ou outras formas alternativas, promovendo maior interacao com o meio e com outras pessoas.",
        image: "/svg/Foguete.svg"
    },
    {
        bgColor: "bg-[var(--dark-green)]",
        title: "2. Reducao de comportamentos desafiadores",
        description:
            "Com tecnicas baseadas em reforco positivo, a terapia ABA busca reduzir comportamentos que atrapalham o aprendizado ou a convivencia social, como agressividade, crises ou estereotipias.",
        image: "/svg/Quebra_Cabecas.svg"
    },
    {
        bgColor: "bg-[var(--blue)]",
        title: "3. Promocao da autonomia e independencia",
        description:
            "A ABA ensina habilidades adaptativas do dia a dia, como se vestir, escovar os dentes, organizar objetos ou seguir rotinas, o que aumenta a independencia da crianca em diferentes contextos.",
        image: "/svg/Balao.svg"
    },
    {
        bgColor: "bg-[var(--green)]",
        title: "4. Melhora do desempenho academico",
        description:
            "Atraves de estrategias individualizadas, a ABA pode ajudar a crianca a desenvolver habilidades academicas, como leitura, escrita e matematica, facilitando seu progresso escolar.",
        image: "/svg/Foguete.svg"
    }
];

export function AbaCards() {
    return (
        <div className="mx-auto grid max-w-7xl gap-4 lg:grid-cols-2">
            {cards.map((card) => (
                <div key={card.title} className={`gap-10 p-6 text-white ${card.bgColor}`}>
                    <div>
                        <ul>
                            <li className="flex flex-row justify-between">
                                <h3 className="text-xl font-bold">{card.title}</h3>
                                <img src={card.image} alt={card.title} className="size-12" />
                            </li>
                        </ul>
                        <p className="text-sm">{card.description}</p>
                    </div>
                </div>
            ))}
        </div>
    );
}

// app/components/AbaCards.vue
<template>
  <div class="max-w-7xl mx-auto grid gap-4 lg:grid-cols-2">
    <div v-for="(card) in cards" :key="card.title" :class="` gap-10 text-white ${card.bgColor} p-6`">
      <div>
        <ul>
          <li class="flex flex-row justify-between">
            <h3 class="font-bold text-xl">
              {{ card.title }}
            </h3>
            <img :src="card.image" :alt="card.title" class="size-12" />
          </li>
        </ul>
        <p class="text-sm">
          {{ card.description }}
        </p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';

const cards = ref([
  {
    bgColor: 'bg-[var(--blue)]',
    title: '1. Desenvolvimento de habilidades sociais e de comunicação',
    description: 'A ABA ajuda a ensinar formas eficazes de se comunicar, seja por meio da fala, gestos ou outras formas alternativas, promovendo maior interação com o meio e com outras pessoas.',
    image: '/svg/Foguete.svg'
  },
  {
    bgColor: 'bg-[var(--dark-green)]',
    title: '2. Redução de comportamentos desafiadores',
    description: 'Com técnicas baseadas em reforço positivo, a terapia ABA busca reduzir comportamentos que atrapalham o aprendizado ou a convivência social, como agressividade, crises ou estereotipias.',
    image: '/svg/Quebra_Cabecas.svg'
  },
  {
    bgColor: 'bg-[var(--blue)]',
    title: '3. Promoção da autonomia e independência',
    description: 'A ABA ensina habilidades adaptativas do dia a dia, como se vestir, escovar os dentes, organizar objetos ou seguir rotinas, o que aumenta a independência da criança em diferentes contextos.',
    image: '/svg/Balao.svg'
  },
  {
    bgColor: 'bg-[var(--green)]',
    title: '4. Melhora do desempenho acadêmico',
    description: 'Através de estratégias individualizadas, a ABA pode ajudar a criança a desenvolver habilidades acadêmicas, como leitura, escrita e matemática, facilitando seu progresso escolar.',
    image: '/svg/Foguete.svg'
  }
]);
</script>
